### ISSUE TITLE
TECH : Uncaught error "no such file or directory"

### ISSUE THREAD

**Issue by neooblaster** [neooblaster/mdmerge#2]
````
$ mdmerge README.master.md
fs.js:114
    throw err;
    ^
Error: ENOENT: no such file or directory, open 'M2020PROD-16_firApproer/README.md'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at readFile (C:\Users\dupreni\Logiciels\NodeJS\node_modules\mdmerge\bin\mdmerge.js:112:20)
    at C:\Users\dupreni\Logiciels\NodeJS\node_modules\mdmerge\bin\mdmerge.js:336:25
    at Array.map (<anonymous>)
    at readFile (C:\Users\dupreni\Logiciels\NodeJS\node_modules\mdmerge\bin\mdmerge.js:239:44)
    at Object.<anonymous> (C:\Users\dupreni\Logiciels\NodeJS\node_modules\mdmerge\bin\mdmerge.js:550:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

````

**Comment by neooblaster** [comment]
Fixed in commit #c6465e0 ([v1.1.3](https://github.com/neooblaster/mdmerge/releases/tag/v1.1.3))
